language: python
python:
  - "3.6"
script:
  - pip install -e git+https://github.com/benchmarking-suite/benchsuite-core.git#egg=benchsuite.core
  - pip install -e .



after_success:

  # trigger the build of docker images
  - "curl --data '{\"docker_tag\": \"dev\"}' -X POST https://cloud.docker.com/api/build/v1/source/e262c94f-53d2-46b1-87f0-cfc601d7c093/trigger/979387fb-5206-4ff9-8570-dda47777498e/call/"